### ISSUE TITLE
Explodes when used in combination with SuperTable

### ISSUE THREAD

**Issue by mattgrayisok** [madmadmad/slugger#1]
When creating a new Entry which has Slugger enabled and the Entry contains a field of type SuperTable the following error is thrown.

Also, thanks for the port :+1: 

```
yii\base\UnknownPropertyException: Getting unknown property: verbb\supertable\elements\SuperTableBlockElement::sectionId in /var/www/html/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/base/Element.php(796): yii\base\Component->__get('sectionId')
#1 /var/www/html/vendor/madhouse/slugger/src/Slugger.php(96): craft\base\Element->__get('sectionId')
#2 [internal function]: madhouse\slugger\Slugger->madhouse\slugger\{closure}(Object(craft\events\ElementEvent))
#3 /var/www/html/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Object(Closure), Object(craft\events\ElementEvent))
#4 /var/www/html/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'afterSaveElemen...', Object(craft\events\ElementEvent))
#5 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(542): yii\base\Component->trigger('afterSaveElemen...', Object(craft\events\ElementEvent))
#6 /var/www/html/vendor/verbb/super-table/src/services/SuperTableService.php(693): craft\services\Elements->saveElement(Object(verbb\supertable\elements\SuperTableBlockElement), false, true)
#7 /var/www/html/vendor/verbb/super-table/src/fields/SuperTableField.php(698): verbb\supertable\services\SuperTableService->saveField(Object(verbb\supertable\fields\SuperTableField), Object(craft\elements\Entry))
#8 /var/www/html/vendor/craftcms/cms/src/base/Element.php(1840): verbb\supertable\fields\SuperTableField->afterElementSave(Object(craft\elements\Entry), true)
#9 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(1046): craft\base\Element->afterSave(true)
#10 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(490): craft\elements\Entry->afterSave(true)
#11 /var/www/html/vendor/craftcms/cms/src/controllers/EntriesController.php(544): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#12 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#13 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('save-entry', Array)
#16 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#17 /var/www/html/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('entries/save-en...', Array)
#18 /var/www/html/vendor/craftcms/cms/src/web/Application.php(541): craft\web\Application->runAction('entries/save-en...', Array)
#19 /var/www/html/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#20 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /var/www/html/web/index.php(21): yii\base\Application->run()
#22 {main}
```

**Comment by mattgrayisok** [comment]
Just looking through the code and it looks like it'll just be a case of removing this assumption that sectionId exists:

https://github.com/madmadmad/slugger/blob/master/src/Slugger.php#L96

**Comment by smockensturm** [comment]
Thanks, Matt.

Added a check for element type. Update and should be good to go.

**Comment by mattgrayisok** [comment]
Nice. Shallow tested and all good so far. Cheers
